FROM nginx:alpine

# Copia el archivo de configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia los archivos estáticos (si es necesario)
COPY /path/to/static/files /app/static
COPY /path/to/media/files /app/media
